package com.trainly.app.ui.designsystem.icons

object TrainlyIcons {
    const val BACK = "\u2190"
    const val CHEVRON_RIGHT = "\u203A"
    const val CLOSE = "\u2716"
    const val PLUS = "+"
    const val SEARCH = "\uD83D\uDD0D"
    const val HOME = "\uD83C\uDFE0"
    const val STATS = "\uD83D\uDCCA"
    const val COMMUNITY = "\uD83D\uDC65"
    const val PROFILE = "\uD83D\uDC64"
    const val SETTINGS = "\u2699\uFE0F"
    const val NOTIFICATION = "\uD83D\uDD14"
    const val RUNNING = "\uD83C\uDFC3"
    const val CYCLING = "\uD83D\uDEB2"
    const val SWIMMING = "\uD83C\uDFCA"
    const val GYM = "\uD83C\uDFCB"
    const val SOS = "\uD83D\uDE91"
    const val ACHIEVEMENT = "\uD83C\uDFC6"
    const val FIRE = "\uD83D\uDD25"
    const val LOCATION = "\uD83D\uDCCD"
    const val CLOCK = "\u23F1"
    const val CALENDAR = "\uD83D\uDCC5"
    const val HEART = "\u2764"
    const val COMMENT = "\uD83D\uDCAC"
    const val LOCK = "\uD83D\uDD12"
    const val EMAIL = "\u2709"
    const val EYE = "\uD83D\uDC41"
    const val EYE_CLOSED = "\uD83D\uDC41\u200D\uD83D\uDDE8"
    const val WARNING = "\u26A0\uFE0F"
    const val EMPTY = "\uD83D\uDCEB"
    const val CHECK = "\u2705"
    const val STAR = "\u2B50"
    const val COFFEE = "\u2615"
    const val STOPWATCH = "\u23F1\uFE0F"
    const val TROPHY = "\uD83C\uDFC6"
    const val MAP = "\uD83D\uDDFA\uFE0F"
    const val FRIENDS = "\uD83D\uDC65"
    const val CAMERA = "\uD83D\uDCF7"
    const val GALLERY = "\uD83D\uDDBC\uFE0F"
    const val SEND = "\u27A1"
    const val PAUSE = "\u23F8\uFE0F"
    const val PLAY = "\u25B6\uFE0F"
    const val STOP = "\u26AB"
}
